services:
  mysql:
    image: mysql:8
    container_name: db2-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tp1
    ports:
      - "3307:3306"
    volumes:
      - db2-mysql-data:/var/lib/mysql

  mongo:
    image: mongo:7
    container_name: db2-mongo
    environment:
      MONGO_INITDB_DATABASE: tp1
    ports:
      - "27018:27017"
    volumes:
      - db2-mongo-data:/data/db

volumes:
  db2-mysql-data:
  db2-mongo-data:
